package projecteuler;
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 */
public class projecteuler002 {
    public static void main(String[] args) {

        Long firt = 1L , last = 2L;

        Long sum = 0L;
        Long sumTwo = 2L;
        while (sum<4000000L){

            sum = firt + last;
            firt = last;
            last = sum;
            if (sum%2 == 0){
                sumTwo = sumTwo + sum;
            }


        }
        System.out.println(sumTwo);

    }
}
